name: currecny_converter_app
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  sentry_flutter: ^8.5.0
  flutter_animate: ^4.5.0
  flutter_launcher_icons: ^0.13.1
  material_symbols_icons: ^4.2771.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11


flutter:

  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"